const BordScrollBar = () => {
  return (
    <div className="w-300 h-200 overflow-auto bg-white-400">
      BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar,
      BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar,
      BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar,
      BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar,
      BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar,
      BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar,
      BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar,
      BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar,
      BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar,
      BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar,
      BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar,
      BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar,
      BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar,
      BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar,
      BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar,
      BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar,
      BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar,
      BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar,
      BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar,
      BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar,
      BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar,
      BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar,
      BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar,
      BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar,
      BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar,
      BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar,
      BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar,
      BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar,
      BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar,
      BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar,
      BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar,
      BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar,
      BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar,
      BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar,
      BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar,
      BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar,
      BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar,
      BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar,
      BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar,
      BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar,
      BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar,
      BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar,
      BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar,
      BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar,
      BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar,
      BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar,
      BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar,
      BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar,
      BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar,
      BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar,
      BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar,
      BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar,
      BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar,
      BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar,
      BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar,
      BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar, BordScrollBar,
      BordScrollBar, BordScrollBar, BordScrollBar,
    </div>
  );
};

export default BordScrollBar;
